### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by dougg0k** [arthurkhlghatyan/gql-client-rs#23]
Hi, any plans on adding proxy support per request?

https://docs.rs/reqwest/latest/reqwest/struct.Proxy.html

**Comment by fewensa** [comment]
I will try to add this feature, thanks for your suggesstion.

**Comment by fewensa** [comment]
Bad news for you. 
https://docs.rs/reqwest/0.11.12/wasm32-unknown-unknown/reqwest/?search=Proxy
the proxy is not supported wasm32 target. so this will only support for without wasm32 platform

**Comment by dougg0k** [comment]
Not really bad news. But ok.
