### ISSUE TITLE
Configure CI to publish crate version on master branch build

### ISSUE THREAD

**Issue by arthurkhlghatyan** [arthurkhlghatyan/gql-client-rs#8]

**Comment by arthurkhlghatyan** [comment]
Still encountering problems in build. Asked the question in this [thread](https://travis-ci.community/t/cannot-publish-rust-crate-using-cargo-provider/10971/2).

**Comment by arthurkhlghatyan** [comment]
Currently, [build](https://travis-ci.com/arthurkhlghatyan/gql-client-rs) is failing because dpl is trying to publish crate on each successful job completion.

**Comment by arthurkhlghatyan** [comment]
Hey, @fewensa have you been able to use Travis for crate publishing before?

**Comment by fewensa** [comment]
> Hey, @fewensa have you been able to use Travis for crate publishing before?

I'm not use Travis, but I can modify use github actions and create a pull request, if you want switch use github action.

**Comment by arthurkhlghatyan** [comment]
Hey @fewensa,

Huge thank you for this update and I will merge this later today or tomorrow (My timezone - in GST)

I couldn't find a way to reach out to you, would you be able to jump on a call with me this week to discuss how we could make the library better and also get to know each other? 

Also worth mentioning I added you as a collaborator to the project and the invite is still pending, let me know if I should re-send.

Arthur.

**Comment by arthurkhlghatyan** [comment]
Hey @fewensa seems there's a problem in configuration syntax. Feel free to open another PR or I can check this in the morning.

**Comment by fewensa** [comment]
Fixed
